### ISSUE TITLE
HI I need help! thankyou

### ISSUE THREAD

**Issue by justbegin01** [000x16x3b/BlackBone#1]
Visual Studio 2022 prompts link error when I compile.

How do I compile this project

**Comment by justbegin01** [comment]
build blackbone project. visual tudio 2022 show me .
error MSB6006: “Lib.exe” close，code 1181。

**Comment by justbegin01** [comment]
I made a mistake, and I fixed it

**Comment by 000x16x3b** [comment]
Lov3yp#3131 plz add mee on discord
